apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detection
  template:
    metadata:
      labels:
        app: fraud-detection
    spec:
      containers:
        - name: fraud-detection
          image: 354918408969.dkr.ecr.us-east-2.amazonaws.com/fraud-detection:latest
          ports:
            - containerPort: 3000
            - containerPort: 5000
