apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-service
spec:
  type: LoadBalancer
  selector:
    app: fraud-detection
  ports:
    - name: web
      protocol: TCP
      port: 3000
      targetPort: 3000  # BentoML server
    - name: api
      protocol: TCP
      port: 5000
      targetPort: 5000  # MLflow UI
