apiVersion: v1
kind: Service
metadata:
  name: fraud-detector-service
spec:
  type: LoadBalancer
  selector:
    app: fraud-detector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # BentoML server
    - protocol: TCP
      port: 81
      targetPort: 5000  # MLflow UI
